default_install_hook_types: [
  pre-commit,
  post-checkout, post-merge, post-rewrite, post-commit]
default_stages: [pre-commit, manual]
exclude: (^tests/.*/.*$)
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.8.2
  hooks:
    - id: uv-sync
      stages: [pre-commit, post-checkout, post-merge, post-rewrite, manual]

- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.8.2
  hooks:
    - id: uv-lock
    - id: uv-export

- repo: local
  hooks:
    - id: static-checks
      name: static-checks
      stages: [pre-commit, pre-push, manual]
      description: >-
        This hook runs all static checks, including mypy, and ruff.
        It is recommended to run this on pre-commit and pre-push.
      always_run: true
      language: python
      entry: uv run tox -m static

    - id: update-version
      name: update-version
      description: >-
        This hook uses the hatch-vcs module to update the `_version.py` file.
        Call this on post-commit and post-checkout.
      stages: [post-commit, post-checkout, post-merge, post-rewrite, manual]
      always_run: true
      language: python
      pass_filenames: false
      entry: uv run --frozen hatch build --hooks-only
